### ISSUE TITLE
Is the source free to edit and use as a personal blog?

### ISSUE THREAD

**Issue by osenv** [brendt/stitcher.io#112]
Hi, this website looks really good! I would wish that I can use the source code for my personal blog as well.

Thanks 👍

**Comment by brendt** [comment]
Hi, thanks!

You can't just copy the styling, if you want to roll your own blog, you'll have to restyle it. PS: my style sheets are a mess.

I'd also advice against using the underlying static generator. I built it 4 or 5 years ago, and am in the process of migrating my blog to another platform. So I won't maintain it anymore.
