### ISSUE TITLE
RSS Feed issue

### ISSUE THREAD

**Issue by ktrzos** [brendt/stitcher.io#129]
Hello! :)
Your RSS feed does not work :).
https://stitcher.io/rss

> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.14. in /home/forge/stitcher.io/vendor/composer/platform_check.php on line 24

All best,
Chris

**Comment by brendt** [comment]
Thanks, it's fixed now!
