### ISSUE TITLE
Broken code blocks on some pages

### ISSUE THREAD

**Issue by marickvantuil** [brendt/stitcher.io#143]
Hey, I noticed some of the pages have broken code blocks:

<img width="924" alt="Screenshot 2021-04-18 at 13 35 16" src="https://user-images.githubusercontent.com/647007/115144085-f26a2a00-a04a-11eb-9457-17c30f722a35.png">

These are the pages where I could find them:

https://stitcher.io/blog/laravel-beyond-crud-07-entering-the-application-layer
https://stitcher.io/blog/laravel-custom-relation-classes
https://stitcher.io/blog/laravel-has-many-through
https://stitcher.io/blog/laravel-beyond-crud-02-working-with-data
https://stitcher.io/blog/tests-and-types
https://stitcher.io/blog/when-i-lost-a-few-hundred-leads
https://stitcher.io/blog/improvements-on-laravel-nova
https://stitcher.io/blog/bitwise-booleans-in-php

**Comment by brendt** [comment]
Thanks for letting me know, don't mind this comment, just makes it easier to open all pages locally :p

http://stitcher.io.test/blog/laravel-beyond-crud-07-entering-the-application-layer
http://stitcher.io.test/blog/laravel-custom-relation-classes
http://stitcher.io.test/blog/laravel-has-many-through
http://stitcher.io.test/blog/laravel-beyond-crud-02-working-with-data
http://stitcher.io.test/blog/tests-and-types
http://stitcher.io.test/blog/when-i-lost-a-few-hundred-leads
http://stitcher.io.test/blog/improvements-on-laravel-nova
http://stitcher.io.test/blog/bitwise-booleans-in-php

**Comment by brendt** [comment]
Thanks again, it's fixed now!
