### ISSUE TITLE
Backed enums `cases()` does not return an associated array.

### ISSUE THREAD

**Issue by thinkverse** [brendt/stitcher.io#147]
In your blog post **PHP Enums** under [Listing enum values](https://stitcher.io/blog/php-enums#listing-enum-values), you wrote that backed-enums return an associative array with its enum values as keys. This might've been the case in an early version of the RFC, but not in the current RFC or the actual enumeration implementation.

After playing around with a PHP 8.1 development build and looking at the Zend test for [backed enum cases](https://github.com/php/php-src/blob/master/Zend/tests/enum/backed-cases-string.phpt), and [pure cases](https://github.com/php/php-src/blob/master/Zend/tests/enum/unit-cases.phpt), reading the RFC, in regards to value listings. Both pure and backed enums return the same packed array, there is no difference between them.

> Both Pure Enums and Backed Enums implement an internal interface named UnitEnum. UnitEnum includes a static method cases(). cases() returns a packed array of all defined Cases in the order of declaration.[1]

1. [RFC: Value listing](https://wiki.php.net/rfc/enumerations#value_listing)

**Comment by brendt** [comment]
Thanks for letting me know! I've fixed that :)
