### ISSUE TITLE
Hi,  may i translate your articles to Simple Chinese ?

### ISSUE THREAD

**Issue by wensonsmith** [brendt/stitcher.io#24]
I really like your laravel beyond curd series, so i translate it into Simple Chinese, and add your blog as original source .

https://iwenson.com/laravel-beyond-curd-preface/

Is it all right to reprint ?

Thank you !

**Comment by brendt** [comment]
Hi there, you can for sure! Please take a look at the rules about translating my content: https://stitcher.io/blog/can-i-translate-your-blog
