### ISSUE TITLE
“👍” is hidden on Firefox

### ISSUE THREAD

**Issue by alexislefebvre** [brendt/stitcher.io#241]
On a post like [this one](https://stitcher.io/blog/dont-be-clever), I see this with Firefox 115.0.2 on Ubuntu 22.04:

> ![image](https://github.com/brendt/stitcher.io/assets/2071331/a283bec6-b8a2-4307-8144-c216b668f1d4)

With Chrome:

> ![image](https://github.com/brendt/stitcher.io/assets/2071331/cdf226c8-adbf-45ab-b5e9-c586e30e755c)

It's probably due to the emoji used by Firefox, or the way the colour is applied to the emoji.

**Comment by brendt** [comment]
Thanks for letting me know! It's fixed :)
