### ISSUE TITLE
#[Override] and static analysis

### ISSUE THREAD

**Issue by Sophist-UK** [brendt/stitcher.io#242]
https://github.com/brendt/stitcher.io/blob/2fd8164b079c79b621e9839ca5ad74ccfc29c9c3/src/content/blog/2023-06-21-override-in-php-83.md?plain=1#L44

I am with you here Brent - IDE analysis is best, static analysis is 2nd best and run -time warnings are worst.

However I suspect that, if a **single** decent static analysis tools was available and used pervasively for all PHP repos, then rules like this (and I suspect many others) could be coded in this tool, and then any pressure for PHP to validate this at run-time would be far lower.

**Comment by brendt** [comment]
Yeah I agree… I don't see that happening anything soon though :(
