### ISSUE TITLE
whitespaces disappeared

### ISSUE THREAD

**Issue by gitetsu** [brendt/stitcher.io#45]
Hi.
First of all, thank you for your great articles!

I've noticed some whitespaces disappeared in the articles like [here](https://github.com/brendt/stitcher.io/blob/master/resources/view/blog/detail.twig#L33)(rendered like `onDecember 07, 2019`) and [here](https://github.com/brendt/stitcher.io/blob/master/resources/view/blog/detail.twig#L92)(like `Next up:Laravel beyond CRUD` but this may not be a problem).

This might be [twig's whitespace-control](https://twig.symfony.com/doc/2.x/templates.html#whitespace-control) but I'm not sure.

I want to fix it if I could, but I'm not familliar with twig, so I just open this.

Again, thank you for the articles.
I'm looking forward to keep reading!

**Comment by brendt** [comment]
Oh thanks for letting me know! I already fixed `onDecember` but wasn't aware of the `next up` button. In the land of template engines I would say this is a breaking change, but oh well… I fixed it by added `&nbsp;` 🙈

Thanks again!
