### ISSUE TITLE
Which is the better (or proper) writing form of arrow functions when in by-reference passing

### ISSUE THREAD

**Issue by zhanglianxin** [brendt/stitcher.io#47]
Hello buddy, I read your post of [*Arrow functions in PHP 7.4*][1] recently. Nice job!

I notice that when using like this:

```php
<?php

$str = 'hello';
(fn&($s) => $s .= ' arrow function')($str);
echo $str . PHP_EOL; // PHP Notice
```

, there's an error reporting: 

```
PHP Notice: Only variable references should be returned by reference in ... on line x
```

, but when I change it to:

```php
<?php

$str = 'hello';
(fn(&$s) => $s .= ' arrow function')($str);
echo $str . PHP_EOL; // hello arrow function
```

, the error is gone, and the output is normal.

So I have the question as the title describes.

[Here][2]'s the Gist code snippet. (My PHP is 7.4.1 on macOS.)

Thanks in advance for your any help.

[1]: https://stitcher.io/blog/short-closures-in-php
[2]: https://gist.github.com/zhanglianxin/4f550ddb1fd6618059fabd19a914d7d4#file-test-fn-php-L16

**Comment by brendt** [comment]
Using `&` outside of the brackets indicates by-reference returning, while `&` inside the parameter list indicates by-refrences passing. https://wiki.php.net/rfc/arrow_functions_v2#function_signatures

I'm not sure when by-reference returning would be useful though.
