### ISSUE TITLE
alternative enum solution

### ISSUE THREAD

**Issue by the-liquid-metal** [brendt/stitcher.io#48]
Hello @brendt.

Recently, i have been revisiting the enum problem. I thing i found my own sollution. Can you read it?
https://gist.github.com/the-liquid-metal/a2608f197e1241d11c956890b7c8a635
Moreover, can you mention it in your [article](https://stitcher.io/blog/php-enums)?

**Comment by brendt** [comment]
There are multiple alternatives, it's good that you're looking for your own! If you'd write a blog post about it, I could share it on Twitter.
