### ISSUE TITLE
Regarding attributes

### ISSUE THREAD

**Issue by moliata** [brendt/stitcher.io#72]
Hello,

After a discussion ([1]: #109880) on internals to rename `PhpAttribute` to `Attribute`, it was decided ([2]: #109987) to use simply `Attribute` instead. It would be great, if you could reflect those changes in the examples (in PHP 8 changes post).

[1]: https://news-web.php.net/php.internals/109880
[2]: https://news-web.php.net/php.internals/109987

Best regards,
Benas Seliuginas

**Comment by brendt** [comment]
Gotcha, thanks for letting me know, it's changed now!
