### ISSUE TITLE
What do you use to write mark down?

### ISSUE THREAD

**Issue by ziachand** [brendt/stitcher.io#90]

**Comment by brendt** [comment]
Commonmark, with several custom parsers: https://github.com/thephpleague/commonmark

**Comment by brendt** [comment]
Custom parsers are here: https://github.com/brendt/stitcher.io/tree/master/src/Plugin/Markdown

**Comment by ziachand** [comment]
thanks, i closed it because i thought its a stupid question :)

**Comment by brendt** [comment]
It's ok, happy to answer :)
