### ISSUE TITLE
Discussion or comments

### ISSUE THREAD

**Issue by roeycohen** [brendt/stitcher.io#99]
Hi @brendt,

First, I really enjoy your blog!

It could be really nice if would add the options to adds comments and make discussions on each post. that way people can add their input and questions...

10x!

**Comment by brendt** [comment]
I thought about this before, but:

- My blog is currently built in my own static generator; it would be a hassle to get comments to work (in fact I have built a working implementation once, but I didn't like it all too much)
- An alternative could be to to rebuild my blog with Laravel, which I also have done before, but I don't like such a bloated stack for such a simple blog.
- Furthermore, I'm a little scared of having to moderate comments, seems like a rabbit hole.

So honestly I'm not sure what to do, I'll remember your question, but I'll close the issue for now.

**Comment by roeycohen** [comment]
hi @brendt, 
you can also consider using an external tool such as Disqus or Commento.
Should be easy enough to embed, and I'm quite positive they have automatic filtering for curses, flooding and etc.

**Comment by brendt** [comment]
I considered it but decided against it. External tools add lots of bloat, and Disqus has a very bad reputation regarding user tracking.

**Comment by roeycohen** [comment]
Well I guess you can't win them all :)
I can just tell about myself that I would love to discuss your threads and I know other people too...

**Comment by brendt** [comment]
How about Twitter?

**Comment by roeycohen** [comment]
Twitter isn't that popular here in Israel...
But if it's works well and can be embedded in the post, so why not? :)
